name: DemoBlaze Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install required libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff1 \
            libopus0 \
            libvpx7 \
            libevent-2.1-7 \
            libgstreamer1.0-0 \
            libgstreamer-plugins-base1.0-0 \
            libgstreamer-plugins-good1.0-0 \
            gstreamer1.0-libav \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-tools \
            gstreamer1.0-x \
            libharfbuzz-icu0 \
            libhyphen0 \
            libmanette-0.2-0 \
            libflite1 \
            libgles2 \
            libx264-dev

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test

